# File: .yamllint.yml
---
extends: default

rules:
  line-length:
    max: 120
    level: error

  # Allow longer lines in certain contexts
  comments:
    min-spaces-from-content: 1

  # Be more lenient with indentation for readability
  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: false

  # Allow multiple spaces for alignment
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Allow empty values (common in Ansible)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # ansible-lint requirements
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

# Ignore certain files
ignore: |
  *.pyc
  .git/
  .github/
  __pycache__/
  collections/
  *.tar.gz
