---
- name: Restart DNS service  # noqa no-changed-when
  ansible.builtin.command:
    argv:
    - rndc
    - reload

- name: Reload NFS exports  # noqa no-changed-when
  ansible.builtin.command:
    cmd: "exportfs -ra"

- name: Update PAM configuration  # noqa no-changed-when
  # N.B. Debian dependent
  ansible.builtin.command:
    cmd: "pam-auth-update --package"
